# Generated by Django 3.1.2 on 2020-10-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='end_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='start_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
