# Generated by Django 3.1.2 on 2020-10-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201008_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kakao_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
