# Generated by Django 3.1.2 on 2020-10-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201010_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
