# Generated by Django 3.1.2 on 2020-10-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201012_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
