# Generated by Django 3.1.2 on 2020-10-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_resume_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
