# Generated by Django 3.1.2 on 2020-10-07 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('category_image', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DetailLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'detail_location',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.category')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=45)),
                ('salary', models.IntegerField(default=0)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.subcategory')),
            ],
            options={
                'db_table': 'salaries',
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('thumbnail_url', models.CharField(max_length=45)),
                ('company_name', models.IntegerField(default=0)),
                ('reward', models.IntegerField(default=0)),
                ('intro', models.TextField()),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('work_area', models.TextField()),
                ('main_work', models.TextField()),
                ('condition', models.TextField()),
                ('preferential_treatment', models.TextField(default='prefer')),
                ('map_url', models.CharField(max_length=500)),
                ('benefits', models.TextField()),
                ('response_rate', models.IntegerField(null=True)),
                ('detail_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.detaillocation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.location')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.subcategory')),
            ],
            options={
                'db_table': 'recruits',
            },
        ),
        migrations.CreateModel(
            name='RecommendRecruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_recruit', to='recruit.recruit')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit', to='recruit.recruit')),
            ],
            options={
                'db_table': 'recommend_recruit',
            },
        ),
        migrations.AddField(
            model_name='detaillocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.location'),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.maincategory'),
        ),
    ]
